### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by luandro** [oviava/react-redux-axios-example#2]
- History package needs to be set to 1.13.x to work with react-router
- No need for function within `<Provider />`
- Use react-dom package

**Comment by oviava** [comment]
hi Luandro, I'll see if I can make some time to update the boilerplate with latest versions. Hopefully by end of this week.

**Comment by nicolasdanelon** [comment]
$ node webpack/server.js 
/home/ndanelon/react-redux-axios-example/node_modules/extract-text-webpack-plugin/index.js:184
		throw new Error("Breaking change: extract now only takes a single argument. Either an options " +
		^

Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
Example: if your old code looked like this:
    ExtractTextPlugin.extract('style-loader', 'css-loader')

You would change it to:
    ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })

The available options are:
    use: string | object | loader[]
    fallback: string | object | loader[]
    publicPath: string

    at Function.ExtractTextPlugin.extract (/home/ndanelon/react-redux-axios-example/node_modules/extract-text-webpack-plugin/index.js:184:9)
    at Object.<anonymous> (/home/ndanelon/react-redux-axios-example/webpack/webpack.config.js:34:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ndanelon/react-redux-axios-example/webpack/server.js:3:14)
error Command failed with exit code 1.

not working again

**Comment by nicolasdanelon** [comment]
what about add a yarn.lock file?
